//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Data.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int OldQuantity { get; set; }
        public int NewQuantity { get; set; }
        public int Change { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Description { get; set; }
        public ActionType ActionType { get; set; }
    
        public virtual Item Item { get; protected set; }
    }
}
