//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Data.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemProperty
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Item Item { get; protected set; }
    }
}
